version: '3.8'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_cobol
    environment:      
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd!
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql/scripts

volumes:
  sql_data:
